// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayPlanner.Api.Data;

#nullable disable

namespace PayPlanner.Api.Migrations
{
    [DbContext(typeof(PaymentContext))]
    [Migration("20250901090000_AddCompaniesAndLinks")]
    partial class AddCompaniesAndLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PayPlanner.Api.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Clients_CreatedAt");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Clients_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Clients_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Clients_Name");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("IX_Clients_IsActive_Name");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Companies_CreatedAt");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Companies_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Companies_Name");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.CompanyClient", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId", "ClientId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CompanyClients_CreatedAt");

                    b.ToTable("CompanyClients");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.CompanyClient", b =>
                {
                    b.HasOne("PayPlanner.Api.Models.Client", "Client")
                        .WithMany("CompanyMemberships")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayPlanner.Api.Models.Company", "Company")
                        .WithMany("Members")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.ClientCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ClientCases_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ClientCases_Status");

                    b.HasIndex("ClientId", "CreatedAt")
                        .HasDatabaseName("IX_ClientCases_ClientId_CreatedAt");

                    b.HasIndex("ClientId", "Status")
                        .HasDatabaseName("IX_ClientCases_ClientId_Status");

                    b.ToTable("ClientCases");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.DealType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_DealTypes_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_DealTypes_Name");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("IX_DealTypes_IsActive_Name");

                    b.ToTable("DealTypes");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.IncomeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_IncomeTypes_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_IncomeTypes_Name");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("IX_IncomeTypes_IsActive_Name");

                    b.HasIndex("IsActive", "PaymentType")
                        .HasDatabaseName("IX_IncomeTypes_IsActive_PaymentType");

                    b.HasIndex("IsActive", "PaymentType", "Name")
                        .HasDatabaseName("IX_IncomeTypes_IsActive_PaymentType_Name");

                    b.ToTable("IncomeTypes");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AccountDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClientCaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DealTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("IncomeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaymentSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaymentStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .HasDatabaseName("IX_Payments_Account");

                    b.HasIndex("AccountDate")
                        .HasDatabaseName("IX_Payments_AccountDate");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Payments_CreatedAt");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Payments_Date");

                    b.HasIndex("DealTypeId")
                        .HasDatabaseName("IX_Payments_DealTypeId");

                    b.HasIndex("IncomeTypeId")
                        .HasDatabaseName("IX_Payments_IncomeTypeId");

                    b.HasIndex("PaymentSourceId")
                        .HasDatabaseName("IX_Payments_PaymentSourceId");

                    b.HasIndex("PaymentStatusId")
                        .HasDatabaseName("IX_Payments_PaymentStatusId");

                    b.HasIndex("Account", "AccountDate")
                        .HasDatabaseName("IX_Payments_Account_AccountDate");

                    b.HasIndex("ClientCaseId", "Date")
                        .HasDatabaseName("IX_Payments_ClientCaseId_Date");

                    b.HasIndex("ClientId", "Date")
                        .HasDatabaseName("IX_Payments_ClientId_Date");

                    b.HasIndex("IsPaid", "Date")
                        .HasDatabaseName("IX_Payments_IsPaid_Date");

                    b.HasIndex("IsPaid", "Status")
                        .HasDatabaseName("IX_Payments_IsPaid_Status");

                    b.HasIndex("Type", "Status", "Date")
                        .HasDatabaseName("IX_Payments_Type_Status_Date");

                    b.HasIndex("ClientCaseId", "Date", "Type", "Status")
                        .HasDatabaseName("IX_Payments_ClientCaseId_Date_Type_Status");

                    b.HasIndex("ClientId", "Date", "Type", "Status")
                        .HasDatabaseName("IX_Payments_ClientId_Date_Type_Status");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.Company", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.PaymentSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_PaymentSources_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_PaymentSources_Name");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("IX_PaymentSources_IsActive_Name");

                    b.ToTable("PaymentSources");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.PaymentStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_PaymentStatuses_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_PaymentStatuses_Name");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("IX_PaymentStatuses_IsActive_Name");

                    b.ToTable("PaymentStatuses");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Name");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime?>("EmploymentEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EmploymentStartDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Instagram")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Messenger")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telegram")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Viber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedAt")
                        .HasDatabaseName("idx_users_approvedAt");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_users_created");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_users_active");

                    b.HasIndex("IsApproved")
                        .HasDatabaseName("idx_users_approval");

                    b.HasIndex("IsEmployee")
                        .HasDatabaseName("idx_users_isemployee");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("idx_users_role");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("idx_users_updated");

                    b.HasIndex("EmploymentStartDate", "EmploymentEndDate")
                        .HasDatabaseName("idx_users_employment_range");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Employment_Range", "(EmploymentStartDate IS NULL OR EmploymentEndDate IS NULL OR EmploymentStartDate <= EmploymentEndDate)");
                        });
                });

            modelBuilder.Entity("PayPlanner.Api.Models.ClientCase", b =>
                {
                    b.HasOne("PayPlanner.Api.Models.Client", "Client")
                        .WithMany("Cases")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.Payment", b =>
                {
                    b.HasOne("PayPlanner.Api.Models.ClientCase", "ClientCase")
                        .WithMany("Payments")
                        .HasForeignKey("ClientCaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PayPlanner.Api.Models.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PayPlanner.Api.Models.DealType", "DealType")
                        .WithMany("Payments")
                        .HasForeignKey("DealTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PayPlanner.Api.Models.IncomeType", "IncomeType")
                        .WithMany("Payments")
                        .HasForeignKey("IncomeTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PayPlanner.Api.Models.PaymentSource", "PaymentSource")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PayPlanner.Api.Models.PaymentStatusEntity", "PaymentStatusEntity")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentStatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("ClientCase");

                    b.Navigation("DealType");

                    b.Navigation("IncomeType");

                    b.Navigation("PaymentSource");

                    b.Navigation("PaymentStatusEntity");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.User", b =>
                {
                    b.HasOne("PayPlanner.Api.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PayPlanner.Api.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.Client", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("CompanyMemberships");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.ClientCase", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.DealType", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.IncomeType", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.PaymentSource", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.PaymentStatusEntity", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PayPlanner.Api.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
