export type Tab =
  | 'calendar'
  | 'reports'
  | 'calculator'
  | 'legalEntities'
  | 'clients'
  | 'accounts'
  | 'acts'
  | 'payments'
  | 'contracts'
  | 'clientDetail'
  | 'users'
  | 'roles'
  | 'userActivity'
  | 'dictionaries';
